"""add doc_number doc_type pages confidence_score to documents and set null on delete

Revision ID: 21afa9436ff1
Revises: 9619962bc431
Create Date: 2026-05-14 13:21:06.359567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21afa9436ff1'
down_revision: Union[str, Sequence[str], None] = '9619962bc431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pages', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('documents', sa.Column('doc_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('documents', sa.Column('doc_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('confidence_score', sa.Float(), nullable=True))
    
    
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('extracted_fields_job_id_fkey'), 'extracted_fields', type_='foreignkey')
    op.create_foreign_key(None, 'extracted_fields', 'extraction_jobs', ['job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extracted_fields', type_='foreignkey')
    op.create_foreign_key(op.f('extracted_fields_job_id_fkey'), 'extracted_fields', 'extraction_jobs', ['job_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    
    op.drop_column('documents', 'confidence_score')
    op.drop_column('documents', 'doc_type')
    op.drop_column('documents', 'doc_number')
    op.drop_column('documents', 'pages')
    # ### end Alembic commands ###
