"""add preprocessed_image_path to extraction_jobs

Revision ID: 61667f57cb1c
Revises: f4b2c1d8a9e0
Create Date: 2026-05-29 11:31:13.149005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61667f57cb1c'
down_revision: Union[str, Sequence[str], None] = 'f4b2c1d8a9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ##
    op.add_column('extraction_jobs', sa.Column('preprocessed_image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extraction_jobs', 'preprocessed_image_path')
    # ### end Alembic commands ###
