"""add soft delete to users and documents

Revision ID: 9374c6244560
Revises: 21afa9436ff1
Create Date: 2026-05-14 21:30:06.471592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9374c6244560'
down_revision: Union[str, Sequence[str], None] = '21afa9436ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('deleted_by', sa.UUID(), nullable=True))
    
    op.create_foreign_key(None, 'documents', 'users', ['deleted_by'], ['id'])
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'is_deleted')
    # ### end Alembic commands ###
