"""add account_enabled to users table

Revision ID: a392cf1ffa64
Revises: 16411a71b637
Create Date: 2026-04-30 13:18:06.541035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'a392cf1ffa64'
down_revision: Union[str, Sequence[str], None] = '16411a71b637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #add acount_enabled column to users table
    op.add_column('users', sa.Column('account_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'account_enabled')
        # ### end Alembic commands ###
